name = "discourse-monitor"
main = "src/index.ts"
compatibility_date = "2026-08-20"

[[d1_databases]]
binding = "DB"
database_name = "discourse-monitor"
database_id = "f630acd7-f0ff-4d25-ae6c-a68fcda7dc38"

[triggers]
crons = ["*/5 * * * *"]
