import type { BarkClient, Forum } from "./monitor";

const escapeHtml = (value: string | number | null | undefined): string => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character);

const layout = (title: string, content: string): string => `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f4f5f7;color:#333;padding:20px;margin:0}.card,.header{max-width:720px;margin:0 auto 20px;background:#fff;padding:20px;border-radius:8px;box-shadow:0 2px 4px #0001}.header{display:flex;align-items:center;justify-content:space-between;background:transparent;box-shadow:none;padding:0}input{width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;box-sizing:border-box}label{font-weight:600;display:block;margin:12px 0 5px}button{background:#007bff;color:#fff;border:0;border-radius:4px;padding:9px 14px;cursor:pointer}button.danger{background:#dc3545}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.item{padding:12px;background:#f9f9f9;border:1px solid #ddd;border-radius:6px;margin:10px 0}.row{display:flex;gap:8px;align-items:center}.row>*{flex:1}.muted{color:#666;font-size:.9em}.error{color:#c62828}.success{color:#27843c}a{color:#007bff;text-decoration:none}@media(max-width:600px){.grid{grid-template-columns:1fr}.row{flex-direction:column;align-items:stretch}}</style></head><body>${content}</body></html>`;

export function loginPage(error?: string): string {
  return layout("登录 - Discourse 监控", `<main class="card" style="max-width:400px;margin-top:12vh"><h2>Discourse 监控控制台</h2>${error ? `<p class="error">${escapeHtml(error)}</p>` : ""}<form method="post" action="/login"><label>用户名</label><input name="username" required autocomplete="username"><label>密码</label><input type="password" name="password" required autocomplete="current-password"><p><button type="submit" style="width:100%">登录</button></p></form></main>`);
}

export function dashboardPage({ forums, clients, settings, stats }: { forums: Forum[]; clients: BarkClient[]; settings: Record<string, string>; stats: Record<string, string> }): string {
  const forumItems = forums.length ? forums.map((forum) => `<div class="item"><strong>${escapeHtml(forum.name)}</strong><div class="muted">${escapeHtml(forum.url)}</div><div class="muted">最新帖子 ID: ${forum.last_topic_id} · 最后检查: ${escapeHtml(forum.last_check_time || "尚未检查")}</div><div class="${forum.error_log === "无" || forum.error_log === "同步ID成功" ? "success" : "error"}">${escapeHtml(forum.error_log)}</div><form method="post" action="/forums/${forum.id}/delete"><button class="danger" type="submit">删除</button></form></div>`).join("") : "<p class=\"muted\">尚未添加任何论坛。</p>";
  const clientItems = clients.length ? clients.map((client) => `<div class="item"><strong>${escapeHtml(client.name)}</strong><div class="muted">Key: ${escapeHtml(client.client_key.slice(0, 8))}********</div><form method="post" action="/clients/${client.id}/delete"><button class="danger" type="submit">删除</button></form></div>`).join("") : "<p class=\"muted\">尚未添加 Bark 设备。</p>";
  return layout("Discourse 监控控制台", `<header class="header"><h1>监控控制台</h1><a href="/logout">退出登录</a></header><main><section class="card"><h2>服务状态</h2><p>最后系统检查：${escapeHtml(stats.global_last_check || "尚未检查")}</p><p>累计总推送：${escapeHtml(stats.total_notified || "0")} 次</p><p>最后推送标题：${escapeHtml(stats.last_notified_title || "无")}</p><div class="row"><form method="post" action="/force-check"><button>立即执行检查</button></form><form method="post" action="/sync-ids"><button>同步所有论坛最新 ID</button></form></div></section><section class="card"><h2>监听论坛</h2>${forumItems}<form method="post" action="/forums"><div class="grid"><div><label>论坛名称</label><input name="name" required></div><div><label>latest.json 地址</label><input name="url" type="url" required placeholder="https://forum.example.com/latest.json"></div></div><p><button>添加论坛</button></p></form></section><section class="card"><h2>全局配置</h2><form method="post" action="/settings"><div class="grid"><div><label>检查间隔（秒，最低 60）</label><input name="check_interval" type="number" min="60" value="${escapeHtml(settings.check_interval || "300")}" required></div><div><label>Bark 节点</label><input name="bark_server" value="${escapeHtml(settings.bark_server)}"></div><div><label>允许推送开始时间</label><input name="push_time_start" type="time" value="${escapeHtml(settings.push_time_start || "00:00")}" required></div><div><label>允许推送结束时间</label><input name="push_time_end" type="time" value="${escapeHtml(settings.push_time_end || "23:59")}" required></div><div><label>Gotify 地址</label><input name="gotify_server" value="${escapeHtml(settings.gotify_server)}"></div><div><label>Gotify Token</label><input name="gotify_token" value="${escapeHtml(settings.gotify_token)}"></div></div><label>Bark 图标 URL</label><input name="bark_icon" value="${escapeHtml(settings.bark_icon)}"><p><button>保存配置</button></p></form></section><section class="card"><h2>Bark 接收设备</h2>${clientItems}<form method="post" action="/clients"><div class="grid"><div><label>设备备注</label><input name="name" required></div><div><label>Bark Key</label><input name="key" required></div></div><p><button>添加设备</button></p></form></section></main>`);
}
